# Generated by Django 4.2.28 on 2026-02-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dose', models.CharField(max_length=100, verbose_name='Dosis (ej. 2ml)')),
                ('frequency_hours', models.PositiveIntegerField(verbose_name='Frecuencia (Horas)')),
                ('start_date', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duración (Días)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tratamiento Activo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramuser')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(verbose_name='Hora Suministro')),
                ('was_late', models.BooleanField(default=False, verbose_name='¿Fue atrasada?')),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramuser')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='health.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha Cita')),
                ('specialist', models.CharField(max_length=100, verbose_name='Especialista (ej. Pediatra)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('notes', models.TextField(blank=True, verbose_name='Diagnóstico/Notas')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Cefálico')),
                ('is_completed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
