# Generated by Django 4.2.28 on 2026-02-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
    ]
