# Generated by Django 4.2.28 on 2026-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Perfil')),
                ('profile_type', models.CharField(choices=[('BABY', 'Bebé'), ('ADULT', 'Adulto')], default='BABY', max_length=10, verbose_name='Tipo')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil (Paciente)',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
