# Generated by Django 4.2.28 on 2026-02-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_config', '0001_initial'),
        ('profiles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LactationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='DiaperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Hora del cambio')),
                ('waste_type', models.CharField(choices=[('PEE', 'Pipí 💧'), ('POO', 'Popó 💩'), ('BOTH', 'Ambos ☣️')], max_length=10)),
                ('size_label', models.CharField(max_length=20, verbose_name='Talla Usada')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaper_logs', to='profiles.profile')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramuser', verbose_name='Quién reportó')),
            ],
        ),
        migrations.CreateModel(
            name='DiaperInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('last_restock', models.DateTimeField(auto_now=True, verbose_name='Última Recarga')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_config.diapersize', verbose_name='Talla')),
            ],
        ),
    ]
