# Generated by Django 4.2.28 on 2026-02-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('profiles', '0001_initial'),
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fin')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='profiles.profile')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Registro de Lactancia',
                'ordering': ['-end_time'],
            },
        ),
    ]
