# Generated by Django 4.2.28 on 2026-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID de Telegram')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuario Telegram')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Real')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo Familiar')),
                ('role', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('GUEST', 'Invitado')], default='GUEST', max_length=10, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario del Bot',
                'verbose_name_plural': 'Usuarios del Bot',
            },
        ),
    ]
