# Generated by Django 4.2.28 on 2026-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, unique=True, verbose_name='Etiqueta Talla')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Disponible en menú?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Talla de Pañal',
                'verbose_name_plural': 'Config: Tallas de Pañales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Clave Config')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Config: Globales',
            },
        ),
    ]
