# Generated by Django 4.2.28 on 2026-02-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LACTATION', 'Recordatorio Lactancia'), ('MEDICATION', 'Recordatorio Medicina'), ('APPOINTMENT', 'Recordatorio Cita'), ('CUSTOM', 'Personalizado')], max_length=20)),
                ('related_id', models.CharField(blank=True, help_text='ID del objeto relacionado (ej. ID del tratamiento)', max_length=50)),
                ('scheduled_time', models.DateTimeField(verbose_name='Hora programada')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Datos extra para el mensaje (ej. Nombre del medicamento)')),
                ('is_sent', models.BooleanField(default=False, verbose_name='¿Enviado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_diapers', models.BooleanField(default=True, verbose_name='Alerta Pañales')),
                ('alert_lactation', models.BooleanField(default=True, verbose_name='Alerta Lactancia')),
                ('alert_meds', models.BooleanField(default=True, verbose_name='Alerta Medicinas')),
                ('alert_appointments', models.BooleanField(default=True, verbose_name='Alerta Citas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to='users.telegramuser')),
            ],
        ),
    ]
